"""
Pydantic schemas for API response serialization.

Reference: architecture_final.md §8.2 (Request/Response Schemas)
"""
from datetime import datetime
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class ProductInput(BaseModel):
    """The input product information provided by the user."""
    mpn: str = Field(..., description="Manufacturer Part Number")
    brand: str = Field(..., description="Brand name")
    description: str = Field(..., description="Short product description")


class EnrichedData(BaseModel):
    """The enriched product intelligence data generated by the pipeline."""
    mpn: str = ""
    brand: str = ""
    manufacturer: str = ""
    category: str = ""
    title: str = ""
    description: str = ""
    long_description: str = ""
    specifications: Dict[str, Any] = Field(default_factory=dict)
    features: List[str] = Field(default_factory=list)
    applications: List[str] = Field(default_factory=list)
    seo_keywords: List[str] = Field(default_factory=list)
    compliance: List[str] = Field(default_factory=list)
    alternate_parts: List[str] = Field(default_factory=list)
    datasheet_url: Optional[str] = None


class ConfidenceScore(BaseModel):
    """Confidence scores for the enriched product data."""
    overall: float = Field(
        default=0.0, ge=0.0, le=1.0,
        description="Overall confidence score (0.0 - 1.0)",
    )
    attributes: Dict[str, float] = Field(
        default_factory=dict,
        description="Per-attribute confidence scores (0.0 - 1.0)",
    )


class ValidationCheck(BaseModel):
    """A single validation check for an attribute."""
    attribute: str = Field(..., description="Attribute name")
    status: str = Field(
        ...,
        description="Verification status: verified, partial, unverified, contradicted",
    )
    message: str = Field(default="", description="Human-readable validation message")


class ValidationReport(BaseModel):
    """The validation report for generated product intelligence."""
    status: str = Field(
        default="passed",
        description="Overall validation status: passed, partial, failed",
    )
    checks: List[ValidationCheck] = Field(
        default_factory=list,
        description="Individual attribute validation checks",
    )
    issues: List[str] = Field(
        default_factory=list,
        description="List of issues found during validation",
    )


class Source(BaseModel):
    """Source attribution for generated data."""
    source_id: str = Field(default="", description="Unique source identifier")
    type: str = Field(
        ...,
        description="Source type: datasheet, vector_db, knowledge_base",
    )
    name: str = Field(default="", description="Human-readable source name")
    url: Optional[str] = Field(default=None, description="Source URL")
    attributes_used: List[str] = Field(
        default_factory=list,
        description="Attributes that were sourced from this source",
    )
    relevance_score: float = Field(
        default=0.0, ge=0.0, le=1.0,
        description="Source relevance score (0.0 - 1.0)",
    )


class AgentTimeline(BaseModel):
    """Agent processing timeline entry."""
    agent: str = Field(..., description="Agent name")
    status: str = Field(default="completed", description="Agent execution status")
    duration_ms: Optional[int] = Field(
        default=None, description="Execution duration in milliseconds",
    )


class ProductResponse(BaseModel):
    """Complete response for the POST /api/v1/analyze endpoint."""
    product_id: str = Field(..., description="Unique product analysis ID")
    status: str = Field(default="completed", description="Analysis status")
    input: ProductInput = Field(..., description="The original input data")
    enriched_data: EnrichedData = Field(..., description="Enriched product intelligence")
    confidence: ConfidenceScore = Field(..., description="Confidence scores")
    validation: ValidationReport = Field(..., description="Validation report")
    sources: List[Source] = Field(default_factory=list, description="Sources used")
    agent_timeline: List[AgentTimeline] = Field(
        default_factory=list, description="Agent processing timeline",
    )
    created_at: str = Field(
        default_factory=lambda: datetime.utcnow().isoformat(),
        description="ISO 8601 creation timestamp",
    )


class ProductHistory(BaseModel):
    """A single analysis history entry."""
    product_id: str = Field(..., description="Unique product analysis ID")
    mpn: str = Field(..., description="Manufacturer Part Number")
    brand: str = Field(..., description="Brand name")
    description: str = Field(..., description="Short product description")
    overall_confidence: float = Field(..., description="Overall confidence score")
    category: Optional[str] = Field(default=None, description="Product category")
    timestamp: str = Field(..., description="ISO 8601 analysis timestamp")
    status: str = Field(default="completed", description="Analysis status")


class HistoryResponse(BaseModel):
    """Paginated response for the GET /api/v1/history endpoint."""
    results: List[ProductHistory] = Field(default_factory=list)
    total: int = 0
    page: int = 1
    limit: int = 10


class DocumentUploadResponse(BaseModel):
    """Response for the POST /api/v1/upload-document endpoint."""
    document_id: str = Field(..., description="Unique document ID")
    filename: str = Field(..., description="Uploaded file name")
    size_bytes: int = Field(..., description="File size in bytes")
    chunks_created: int = Field(..., description="Number of chunks created")
    status: str = Field(..., description="Processing status")
    mpn: Optional[str] = Field(default=None, description="Associated MPN")


class HealthResponse(BaseModel):
    """Response for the GET /api/v1/health endpoint."""
    status: str = Field(..., description="Application health status")
    version: str = Field(..., description="Application version")
    uptime: int = Field(..., description="Uptime in seconds")
    chromadb: str = Field(..., description="ChromaDB connection status")
    gemini: str = Field(..., description="Gemini API availability status")

